### ISSUE TITLE
gTest with the YY mode

### ISSUE THREAD

**Issue by sanghoun** [goodmami/gtest#6]
art can be run in the YY mode, in orde to parse the sentences with unknown work handling. 
The command for running art with the YY inputs is as follows.

$ art -Ya "python utils/cmn2yy.py | ace -g zhs.dat -y" /PATH/TO/PROFILE_TO_WRITE

So, it would be good that gTest can work with this kind of processing as an option or whatever. 

For example, 

./gTest -G ~/zhs -C :zhs.dat -W ../tsdb/gtest/unk -Y "python utils/cmn2yy.py" C :mrs

**Comment by goodmami** [comment]
This sounds good, but maybe I'll separate the setting of YY-mode (which sets `-Y` on `art` and `-y` on ACE) from the preprocessor:

`./gTest -G ~/zhs -C :zhs.dat -W ../tsdb/gtest/unk -Y -P "python utils/cmn2yy.py" C :mrs`
